-- liquibase formatted sql

-- changeset aryazanov:1
CREATE TABLE IF NOT EXISTS socks (
                                     id Integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     color varchar not null unique,
                                     cotton_part  integer not null,
                                     sock_count bigint default 0
);